# SERVER
server:
  servlet:
    context-path: /api

# DB
spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  profiles:
#    include:
#      - redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # server
#    url: jdbc:mysql://j8a108.p.ssafy.io:3306/finedui?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # local
    url: jdbc:mysql://localhost:3306/cigma?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
#      pool-name: fined&youHikariPool
  jpa:
    defer-datasource-initialization: true
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        #        SQL ??? ??? ????? ???
        format_sql: true
        #
        show-sql: false
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# log level ??
logging:
  level:
    org:
      # security log level ??
      springframework:
        security: DEBUG
#      # hibernate log level ??
#      hibernate:
#        SQL: DEBUG
#      # ???? ???? ??.
#      # AWS
#    com:
#      amazonaws:
#        util:
#          EC2MetadataUtils: ERROR

# jwt 관련
jwt:
  header: Authorization
  secret: Y2lnbWEtc3ByaW5nLWJvb3Qtand0LXNlY3JldC1rZXktY2lnbWEtc3ByaW5nLWJvb3Qtand0LXNlY3JldC1rZXktYnktYWpoCg==
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 8640000